boostorg/smart_ptr

include/boost/smart_ptr/detail/yield_k.hpp
This fixes a problem with the latest clang built from source. It also works fine with previous versions of clang on Windows. I will test this again once clang 3.7 is official but since it works with clang 3.4.1, clang 3.5.2, and clang 3.6.1 on Windows I doubt it will cause any problems once clang 3.7 on Windows is officially released. Needless to say this does not affect clang outside of Windows at all.
=> Added __declspec(dllimport) for Sleep using clang on Windows.

include/boost/smart_ptr/detail/operator_bool.hpp
Although Oracle supports this syntax, advanced usage such as:
if(my_shared_ptr && x)
Fail.  Attempts to wokaround by adding additional operator overloads have so far failed.
=> Disable explicit operator bool on Oracle C++

include/boost/smart_ptr/detail/sp_interlocked.hpp
-> MSVC 7.1 has no intrin.h and needs to use "#pragma intrinsic".
-> intrin.h available since Visual 2005
=> Support MSVC-7.1/ intrin.h available >= MSVC-8.0

include/boost/smart_ptr/shared_ptr.hpp, shared_ptr.htm, test/Jamfile.v2, test/shared_ptr_alias_move_test.cpp
As per discussion in http://article.gmane.org/gmane.comp.lib.boost.devel/263684; this seems like something that should exist even though use cases are slim.
=> Added shared_ptr aliasing move constructor.

include/boost/smart_ptr/intrusive_ptr.hpp
Analagous to template <class U> intrusive_ptr(intrusive_ptr<U> const&).
Requires a template friend declaration for intrusive_ptr<U>.
=> intrusive_ptr: add converting ctor for intrusive_ptr<U> with move semantics

include/boost/smart_ptr/bad_weak_ptr.hpp, include/boost/smart_ptr/detail/sp_counted_base_clang.hpp
Fixes following warnings:
```
In file included from qi/actions2.cpp:20:
In file included from ../../../boost/spirit/include/qi.hpp:16:
In file included from ../../../boost/spirit/home/qi.hpp:28:
In file included from ../../../boost/spirit/home/qi/string.hpp:15:
In file included from ../../../boost/spirit/home/qi/string/symbols.hpp:30:
In file included from ../../../boost/shared_ptr.hpp:17:
In file included from ../../../boost/smart_ptr/shared_ptr.hpp:28:
In file included from ../../../boost/smart_ptr/detail/shared_count.hpp:29:
In file included from ../../../boost/smart_ptr/detail/sp_counted_base.hpp:45:
../../../boost/smart_ptr/detail/sp_counted_base_clang.hpp:61:7: warning: 'sp_counted_base' has no out-of-line virtual method definitions; its vtable will be emitted in every translation …
```
=> Suppress weak vtables warnings

include/boost/smart_ptr/make_shared_object.hpp
Currently, boost::make_shared doesn't perform constructor forwarding unless C++11 r-value references are supported. This prevents using of MOVABLE_BUT_NOT_COPYABLE types as arguments to constructors.
The Boost.Move documentation describes [how to perform (limited) constructor forwarding](http://www.boost.org/doc/libs/1_59_0/doc/html/move/construct_forwarding.html). It's example is perfectly applicable to boost::make_shared.
This PR implements constructor forwarding for make_shared as documented in Boost.Move's documentation.
With this change the difference between the code supporting r-value references but not supporting variadic templates became the type signature and the call to boost::detail::sp_forward and boost::forward. The first difference was eliminated by using the macro …
=> boost::make_shared: use Constructor Forwarding on C++03

test/Jamfile.v2, test/make_shared_move_emulation_test.cpp
As requested by @pdimov.
This tests the functionality added with PR boostorg/smart_ptr#24.
Specifically this tests that passing moveable-only types to
constructors is possible through make_shared. Note that real rvalue's
still cannot be passed that way on C++03 unfortunately because there's
no generic way of accomplishing that with current move emulation.
=> Add test for make_shared's move-emulation support

test/Jamfile.v2, test/shared_ptr_reinterpret_pointer_cast_test.cpp
Based on existing pointer_cast tests in shared_ptr_test.cpp
=> Add explicit tests for reinterpret_pointer_cast

include/boost/smart_ptr/shared_ptr.hpp, test/Jamfile.v2, test/shared_ptr_rv_pointer_cast_test.cpp
I came across this today when looking to optimize some code. This saves an atomic increment + decrement on each cast.
Then I discovered there's a similar proposal for std here:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0390r0.htm
While I was in there, I noticed that there is no test for reinterpret_pointer_cast. Do we want one?
=> Add rvalue versions of static_pointer_cast, const_pointer_cast, dynamic_pointer_cast, reinterpret_pointer_cast. 

include/boost/smart_ptr/detail/sp_counted_base.hpp, include/boost/smart_ptr/detail/sp_has_sync.hpp
Clang/C2 in VS2015 defines __c_atomic__, but can't really use it. Disable __c_atomic__ and BOOST_SP_HAS_SYNC for Clang/C2 to fix 2 compiler internal errors.
=> Fix compiling problems under ClangC2.

include/boost/smart_ptr/detail/sp_has_sync.hpp
The library currently defines BOOST_SP_HAS_SYNC for IBM z/OS XL C/C++, which doesn't support the \_\_sync intrinsics. Adding _&& !defined( \_\_COMPILER\_VER\_\_ )_ to the condition should prevent that.
(According to https://sourceforge.net/p/predef/wiki/Compilers/ _\_\_COMPILER\_VER\_\__ is only defined by IBM z/OS XL C/C++)
=> don't define BOOST_SP_HAS_SYNC for z/OS XL C/C++ compiler

include/boost/smart_ptr/allocate_shared_array.hpp, include/boost/smart_ptr/detail/shared_count.hpp, include/boost/smart_ptr/detail/sp_counted_impl.hpp, test/Jamfile.v2, test/shared_ptr_alloc_construct11_test.cpp
Since DR 2070 was first posted, the pattern for using allocators for construct and destroy has changed to only use them for the value_type (and placement new for all other node types).
Also only use allocate(n) instead of allocate(n, nullptr) since that former should be sufficient for C++98 and beyond.
=> Only use allocator construct/destroy for value_type (not shared_count)

include/boost/smart_ptr/bad_weak_ptr.hpp
Building with Intel c++ on Mac generates numerous warnings of this flavor:
In file included from /Users/kbelco/Projects/local/boost/include/boost/smart_ptr/detail/shared_count.hpp(28),
from /Users/kbelco/Projects/local/boost/include/boost/smart_ptr/shared_ptr.hpp(28),
from /Users/kbelco/Projects/local/boost/include/boost/shared_ptr.hpp(17),
from /Users/kbelco/Projects/edr/src/edr/json_spirit_v4.08/json_spirit/json_spirit_value.h(21),
from /Users/kbelco/Projects/edr/src/edr/json_spirit_v4.08/json_spirit/json_spirit_writer.h(13),
from /Users/kbelco/Projects/edr/src/edr/json_spirit_v4.08/json_spirit/json_spirit_writer.cpp(6):
/Users/kbelco/Projects/local/boost/include/boost/smart_ptr/bad_weak_ptr.hpp(57): warning #161: unrecognized #pragma
^
This patch silences the warnings.
=> Protect clang pragmas with BOOST_CLANG macro.

include/boost/smart_ptr/detail/atomic_count_gcc.hpp
Nearly every header in the boost codebase is UTF-8, but here there
are a few headers which are using Windows-1252, which makes it impossible
for some tools to parse those files. This patch just reencodes them
with UTF-8 like the rest of the codebase. I checked that the name of the
author is still correct after this change.
No functional change intended.
=> Reencoded a few headers that used Windows-1252 with UTF-8.

include/boost/smart_ptr/detail/local_counted_base.hpp
nvcc seems to use the host compiler for preprocessing the source for the device and host compilation.
When compiling the host code with the host compiler (clang), `__builtin_assume` is detected correctly and is also available during compilation.
When compiling the device code with nvcc, this builtin function is not provided by nvcc.
=> fix compilation for nvcc+clang

include/boost/smart_ptr/allocate_shared_array.hpp
We should also add a convenient is_trivial to Boost.TypeTraits.
=> sp_array_construct condition for trivial should include has_trivial_destructor

include/boost/smart_ptr/detail/sp_counted_base_gcc_mips.hpp
MIPS r6 changed the encoding for `ll' instruction,
if we `.set mips2', it will generate the old encoding for `ll'.
So here we disable it for r6.
=> disable .set mips2 for mips release r6

include/boost/smart_ptr/detail/atomic_count_std_atomic.hpp
* fix implicit conversion warning
=> atomic_count_std_atomic: static_cast v to std::int_least32_t

include/boost/smart_ptr/detail/shared_count.hpp, include/boost/smart_ptr/detail/sp_counted_impl.hpp, include/boost/smart_ptr/scoped_array.hpp, include/boost/smart_ptr/scoped_ptr.hpp, include/boost/smart_ptr/shared_array.hpp, include/boost/smart_ptr/shared_ptr.hpp
boost/checked_delete.hpp has been deprecated:
```cpp
#ifndef BOOST_CHECKED_DELETE_HPP
#define BOOST_CHECKED_DELETE_HPP
// The header file at this path is deprecated;
// use boost/core/checked_delete.hpp instead.
#include <boost/core/checked_delete.hpp>
#endif
```
=> refactor: use boost/core/checked_delete.hpp over boost/checked_delete.hpp

include/boost/smart_ptr/detail/sp_counted_base_cw_ppc.hpp
Un-obsoletes `sp_counted_base_cw_ppc.hpp` as well.
Fixes #94.
=> Add support for different sync instructions for CodeWarrior PPC

include/boost/smart_ptr/intrusive_ptr.hpp
Unreal Engine 5 gives following error.
```
boost\smart_ptr\intrusive_ptr.hpp(248): error C4668: 'GNUC' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
```
=> Add missing ifdef check.

include/boost/smart_ptr/detail/sp_has_gcc_intrinsics.hpp
Mirroring [dealii/dealii@`e969195` (#16621)](https://github.com/dealii/dealii/pull/16621/commits/e969195f058cfa491dad3580797b1190224ef4b9). We were running into errors like
```
D:\a\dealii\dealii\bundled\boost-1.84.0\include\boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp(35,5): error C3861: '__atomic_fetch_add': identifier not found [D:\a\dealii\dealii\build\source\numerics\object_numerics_debug.vcxproj]
D:\a\dealii\dealii\bundled\boost-1.84.0\include\boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp(40,12): error C3861: '__atomic_fetch_sub': identifier not found [D:\a\dealii\dealii\build\source\numerics\object_numerics_debug.vcxproj]
D:\a\dealii\dealii\bundled\boost-1.84.0\include\boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp(49,31): error C3861: '__atomic_load_n': …
```
=> Don't define BOOST_SP_HAS_GCC_INTRINSICS for MSVC
